### ISSUE TITLE
--data-binary unsupported

### ISSUE THREAD

**Issue by Kreijstal** [kigiri/fetch#7]
it's simply ignored, maybe can it failsafe to --data?
  
Also it doesn't specifies the action of the HTTP request, it should say POST at least.

**Comment by kigiri** [comment]
I'll look into it

**Comment by kigiri** [comment]
I pushed an update that should handle --data-binary
From my very simple tests it worked fine, thank you for pointing that out.

*(copy pasted from a chrome request as CURL)*
`curl 'https://supervisor.oct.ovh/env' -H 'origin: http://localhost:1234' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en;q=0.9,en-US;q=0.8,fr;q=0.7' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3316.0 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'referer: http://localhost:1234/' -H 'authority: supervisor.oct.ovh' -H 'cookie: __cfduid=daf73c6717494883150264465b9109f057fd8956516; 4k=XSXSXS' --data-binary '{"name":"supervisor","env":"some-serious-env-lol"}' --compressed`

Output
```js
{ method: 'GET',
  headers: 
   { 'Content-Type': 'application/json',
     Accept: 'application/json' },
  url: 'https://supervisor.oct.ovh/env',
  credentials: 'include',
  body: '{"name":"supervisor","env":"some-value"}' }
```
